import { InvestigationResult } from '../types';
import {
  CLAIM_KIND_LABEL,
  plainStatus,
  EXTRACTION_STATUS,
  OUTCOME,
  RELATION,
  RETRIEVAL,
  SOURCE_KIND,
  SOURCE_TIER,
} from './labels';

const EMAIL = /[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}/g;
// UPI handles look like name@bank, with no dot after the @.
const UPI = /[A-Za-z0-9._-]{2,}@[A-Za-z]{2,}(?![A-Za-z0-9.])/g;
const PHONE = /(?<![\w-])(?:\+?91[\s-]?)?[6-9]\d{4}[\s-]?\d{5}(?![\w-])/g;

/**
 * Strip personal contact identifiers before a report leaves the app. The
 * employer-published confirmation destination is kept: it is public and is the
 * whole point of the export.
 */
export function redactContacts(text: string, keep: string[] = []): string {
  const kept = new Set(keep.filter(Boolean).map((k) => k.toLowerCase()));
  const swap = (label: string) => (match: string) => (kept.has(match.toLowerCase()) ? match : `[${label} removed]`);
  return text.replace(EMAIL, swap('email')).replace(UPI, swap('UPI ID')).replace(PHONE, swap('phone'));
}

export interface ExportOptions {
  title: string;
  /** Keep sender emails/phones/UPI IDs, e.g. for a cybercrime complaint. */
  includeContacts: boolean;
  generatedAt?: string | null;
  version?: number;
  sample?: boolean;
}

/** Plain Markdown report: readable anywhere, easy to attach to a complaint. */
export function buildMarkdownReport(result: InvestigationResult, options: ExportOptions): string {
  const evidenceById = new Map(result.evidence.map((e) => [e.evidence_id, e]));
  const assessmentById = new Map(result.assessed_claims.map((a) => [a.claim_id, a]));
  const outcome = OUTCOME[result.overall_outcome];
  const lines: string[] = [];

  lines.push(`# AsliOffer report: ${options.title}`, '');
  if (options.sample) lines.push('> Illustrative sample built from synthetic data. Not a real investigation.', '');
  if (result.demo_mode) lines.push('> Demo mode: evidence in this report is demo data, not a live search.', '');
  lines.push(`- **Outcome:** ${outcome.label}. ${outcome.summary}`);
  lines.push('- **Authenticity:** Unconfirmed. Only the employer can confirm an offer.');
  lines.push(
    `- **Coverage:** ${result.coverage.checked_claims} of ${result.coverage.total_claims} claims checked, ` +
      `${result.coverage.unresolved_claims} unresolved, ${result.coverage.failed_checks} failed checks. ` +
      'Coverage measures completeness, not the chance of fraud.',
  );
  if (options.version) lines.push(`- **Report version:** ${options.version}`);
  if (options.generatedAt) lines.push(`- **Finished:** ${new Date(options.generatedAt).toISOString()}`);
  lines.push('');

  if (result.errors.length) {
    lines.push('## Checks that did not complete', '');
    result.errors.forEach((e) => lines.push(`- ${e.message}${e.step ? ` (step: ${e.step})` : ''}`));
    lines.push('');
  }

  lines.push('## Claims', '');
  for (const claim of result.claims) {
    const assessment = assessmentById.get(claim.claim_id);
    const status = plainStatus(claim, assessment).label;
    lines.push(`### ${CLAIM_KIND_LABEL[claim.kind]}: ${claim.value ?? '(not in the offer)'}`, '');
    lines.push(`- **Status:** ${status}`);
    lines.push(`- **Extraction:** ${EXTRACTION_STATUS[claim.extraction_status]}`);
    if (claim.source_quote) lines.push(`- **Quote:** "${claim.source_quote}"`);
    if (assessment) lines.push(`- **Assessment:** ${assessment.explanation}`);
    const cited = (assessment?.evidence_ids ?? []).map((id) => evidenceById.get(id)).filter(Boolean);
    for (const ev of cited) {
      if (!ev) continue;
      lines.push(
        `  - ${RELATION[ev.relation].label} — ${ev.title} (${SOURCE_KIND[ev.source_kind]}, ${SOURCE_TIER[ev.source_tier]}, ` +
          `${RETRIEVAL[ev.retrieval_status]}, ${new Date(ev.retrieved_at).toISOString()})` +
          (ev.source_url ? ` <${ev.source_url}>` : ''),
      );
      if (ev.quote_or_snippet) lines.push(`    > ${ev.quote_or_snippet.replace(/\n/g, ' ')}`);
    }
    lines.push('');
  }

  if (result.recommended_actions.length) {
    lines.push('## Recommended next steps', '');
    result.recommended_actions.forEach((a, i) => lines.push(`${i + 1}. ${a}`));
    lines.push('');
  }

  const route = result.confirmation_route;
  lines.push('## Confirming with the employer', '');
  if (route) {
    const ev = evidenceById.get(route.evidence_id);
    lines.push(`- **Channel:** ${route.channel.replace(/_/g, ' ')}`);
    lines.push(`- **Destination:** ${route.destination}`);
    if (ev?.source_url) lines.push(`- **Published at:** <${ev.source_url}>`);
  } else {
    lines.push('No employer-published confirmation channel was found in this investigation.');
  }
  lines.push('', '---', 'Generated by AsliOffer. Report suspected fraud at https://cybercrime.gov.in or call 1930.');

  const markdown = lines.join('\n');
  return options.includeContacts ? markdown : redactContacts(markdown, route ? [route.destination] : []);
}

export function downloadText(filename: string, content: string, type = 'text/markdown') {
  const blob = new Blob([content], { type: `${type};charset=utf-8` });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

/** Opens the print dialog on the report page; the page title becomes the suggested PDF file name. */
export function downloadPdf(filename: string) {
  const previous = document.title;
  document.title = filename;
  window.addEventListener('afterprint', () => (document.title = previous), { once: true });
  window.print();
}
